version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    depends_on:
      - postgres
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'

volumes:
  postgres_data:
    driver: local
